// Английские подписи панели настроек. Ключ это русская строка из settings.html или settings.js
window.SETTINGS_EN = {
    'Настройки': 'Settings',
    'Закрыть, F1 или Esc': 'Close, F1 or Esc',
    'Закрыть настройки': 'Close settings',
    'Нужна перезагрузка страницы': 'Page reload needed',
    'Перезагрузить': 'Reload',
    'Разделы настроек': 'Settings sections',
    'Основное': 'General',
    'Главная': 'Home',
    'Моя волна': 'My Wave',
    'Темы и плагины': 'Themes and plugins',
    'Аккаунт': 'Account',
    'Дополнительно': 'Advanced',

    'Тёмная тема': 'Dark theme',
    'Сворачивать в трей': 'Minimize to tray',
    'Кнопки навигации в шапке': 'Navigation buttons in the title bar',
    'Меньше анимаций': 'Reduce motion',

    'Язык': 'Language',
    'Блокировать рекламу': 'Block ads',
    'Скрывать рекламные блоки': 'Hide promoted blocks',
    'Скрывать концерты поблизости': 'Hide events near you',
    'Скрывать предложения Artist Pro': 'Hide Artist Pro offers',
    'Перемешивать всю очередь': 'Shuffle the whole queue',
    'Сам SoundCloud перемешивает только загруженные треки': 'SoundCloud itself shuffles only the loaded tracks',

    // Названия полок как на английском сайте
    'Полки': 'Shelves',
    'Больше того, что тебе нравится': 'More of what you like',
    'Недавно играло': 'Recently played',
    'Миксы для тебя': 'Mixed for you',
    'Станции': 'Stations',
    'В тренде по жанрам': 'Trending by genre',
    'Для тебя': 'Made for you',
    'Подборки SoundCloud': 'Curated by SoundCloud',
    'Альбомы для тебя': 'Albums for you',
    'Лайкнули': 'Liked by',
    'Артисты, за которыми стоит следить': 'Artists to watch out for',
    'Справа': 'Sidebar',
    'Новые треки': 'New tracks',
    'Кого послушать': 'Artists you should follow',
    'Лайки': 'Likes',
    'История прослушивания': 'Listening history',
    'SoundCloud на телефоне и подвал': 'Mobile apps and footer',

    'Показывать на главной': 'Show on Home',
    'Не нравится': 'Disliked',
    'Скрытые артисты': 'Hidden artists',
    'Пусто': 'Empty',
    'Трек': 'Track',
    'Артист': 'Artist',
    'Вернуть': 'Restore',

    'Показывать трек в статусе': 'Show track in status',
    'Значок SoundCloud на обложке': 'SoundCloud badge on artwork',
    'Значок GitHub со ссылкой на клиент': 'GitHub badge linking to the client',
    'Кнопка перехода к треку': 'Button to open the track',
    'Вторая строка под ником': 'Second line under your name',
    'Listening to Drake вместо Listening to SoundCloud': 'Listening to Drake instead of Listening to SoundCloud',
    'Инкогнито': 'Incognito',
    'Строки карточки': 'Card lines',
    'Первая': 'First',
    'Вторая': 'Second',
    'На обложке': 'On artwork',
    'Подсказка при наведении': 'Tooltip on hover',
    'Название трека': 'Track title',
    'Жанр': 'Genre',
    'Моя волна, если трек из неё': 'My Wave, if the track comes from it',
    'Прослушивания': 'Plays',
    'Как было': 'Reset',
    'Не показывать в Discord': 'Hide from Discord',
    'Артисты через запятую': 'Artists, comma separated',
    'Артисты, которых не видно в Discord': 'Artists hidden from Discord',
    'Жанры через запятую': 'Genres, comma separated',
    'Жанры, которых не видно в Discord': 'Genres hidden from Discord',
    'Инкогнито: Discord не видит, что играет': 'Incognito: Discord doesn’t see what’s playing',
    'Артист в списке скрытых, Discord его не видит': 'This artist is hidden, Discord doesn’t see it',
    'Жанр в списке скрытых, Discord его не видит': 'This genre is hidden, Discord doesn’t see it',
    'Так статус видят в Discord': 'How your status looks in Discord',
    'Сейчас ничего не играет': 'Nothing is playing',
    'Обложка трека': 'Track artwork',
    'Слушать в SoundCloud': 'Listen on SoundCloud',
    'SoundCloud на GitHub': 'SoundCloud on GitHub',
    'Без названия': 'Untitled',
    'Неизвестный артист': 'Unknown artist',
    'Под ником:': 'Under your name:',

    'Своя тема': 'Custom theme',
    'Без темы': 'No theme',
    'Открыть папку тем': 'Open themes folder',
    'Перечитать папку тем': 'Reload themes folder',
    'Плагины': 'Plugins',
    'Открыть папку плагинов': 'Open plugins folder',
    'Перечитать папку плагинов': 'Reload plugins folder',
    'Папка плагинов пуста': 'The plugins folder is empty',
    'Открыть страницу плагина': 'Open plugin page',
    'Автор:': 'Author:',

    'Текущий аккаунт': 'Current account',
    // Имена аккаунтов по умолчанию, остальные имена это ники с сайта
    'Основной аккаунт': 'Main account',
    'Новый аккаунт': 'New account',
    'Добавить аккаунт': 'Add account',
    'Выйти': 'Log out',
    'Смена аккаунта перезапускает клиент': 'Switching accounts restarts the client',

    'Разбирать названия треков': 'Parse track titles',
    'Отделяет артиста от названия, когда оба в одной строке': 'Separates the artist from the title when both are in one line',
    'Подключаться через прокси': 'Connect through a proxy',
    'Адрес': 'Host',
    'Адрес прокси': 'Proxy host',
    'Порт': 'Port',
    'Порт прокси': 'Proxy port',
    'Логин': 'Username',
    'Логин прокси': 'Proxy username',
    'Пароль': 'Password',
    'Пароль прокси': 'Proxy password',
    'Отправлять вебхук': 'Send a webhook',
    'https://адрес-вебхука': 'https://webhook-url',
    'Адрес вебхука': 'Webhook URL',
    'Когда трек проигран на': 'When the track has played',
    'Процент проигрывания': 'Played percentage',
    'Пример данных': 'Sample data',
    'Журнал диагностики': 'Diagnostic log',
    'Ошибки и нагрузка, без паролей и названий треков': 'Errors and load, without passwords or track titles',
    'Сохранить': 'Save',
    'Журнал сохранён, его можно отправить для разбора проблемы': 'Log saved, you can send it to have the problem looked into',
    'Не удалось сохранить журнал, попробуй другую папку': 'Couldn’t save the log, try another folder',
    'Папка данных клиента': 'Client data folder',
    'Настройки, темы и плагины': 'Settings, themes and plugins',
    'Открыть': 'Open',

    'Проверять обновления': 'Check for updates',
    'Проверить сейчас': 'Check now',
    'Страница релиза': 'Release page',
    'Версия': 'Version',
};
