// Английские подписи панели настроек. Ключ это русская строка из settings.html или settings.js
window.SETTINGS_EN = {
    'Настройки': 'Settings',
    'Закрыть, F1 или Esc': 'Close, F1 or Esc',
    'Закрыть настройки': 'Close settings',
    'Нужна перезагрузка страницы': 'Page reload needed',
    'Перезагрузить': 'Reload',
    'Разделы настроек': 'Settings sections',
    'Основное': 'General',
    'Главная': 'Home',
    'Моя волна': 'My Wave',
    'Аккаунт': 'Account',
    'Дополнительно': 'Advanced',

    'Сворачивать в трей': 'Minimize to tray',
    'Кнопки навигации в шапке': 'Navigation buttons in the title bar',
    'Меньше анимаций': 'Reduce motion',
    'Совместимость NVIDIA': 'NVIDIA compatibility',
    'Автоматически': 'Automatic',
    'Включено': 'On',
    'Выключено': 'Off',
    'Применится после перезапуска.': 'Applies after restarting the client.',
    'Доступно на Windows.': 'Available on Windows.',
    'Отключено после аварийного завершения.': 'Disabled after an unexpected shutdown.',
    'Включено автоматически для NVIDIA.': 'Enabled automatically for NVIDIA.',
    'Включено.': 'Enabled.',
    'Выключено.': 'Disabled.',
    'Не удалось определить видеокарту.': 'Could not detect the graphics adapter.',
    'NVIDIA не обнаружена.': 'NVIDIA not detected.',
    'Отключено параметром запуска.': 'Disabled by a launch argument.',

    'Язык': 'Language',
    'Блокировать рекламу': 'Block ads',
    'Скрывать рекламные блоки': 'Hide promoted blocks',
    'Скрывать концерты поблизости': 'Hide events near you',
    'Скрывать предложения Artist Pro': 'Hide Artist Pro offers',
    'Скрывать Go+, Artist Studio и загрузку в шапке': 'Hide Go+, Artist Studio and Upload in the header',
    'Перемешивать всю очередь': 'Shuffle the whole queue',
    'Сам SoundCloud перемешивает только загруженные треки': 'SoundCloud itself shuffles only the loaded tracks',

    // Названия полок как на английском сайте
    'Полки': 'Shelves',
    'Больше того, что тебе нравится': 'More of what you like',
    'Недавно играло': 'Recently played',
    'Миксы для тебя': 'Mixed for you',
    'Станции': 'Stations',
    'В тренде по жанрам': 'Trending by genre',
    'Для тебя': 'Made for you',
    'Подборки SoundCloud': 'Curated by SoundCloud',
    'Альбомы для тебя': 'Albums for you',
    'Лайкнули': 'Liked by',
    'Артисты, за которыми стоит следить': 'Artists to watch out for',
    'Справа': 'Sidebar',
    'Новые треки': 'New tracks',
    'Кого послушать': 'Artists you should follow',
    'Лайки': 'Likes',
    'История прослушивания': 'Listening history',
    'SoundCloud на телефоне и подвал': 'Mobile apps and footer',

    'Показывать на главной': 'Show on Home',
    'Не нравится': 'Disliked',
    'Скрытые аккаунты': 'Hidden accounts',
    'Только эта версия': 'Only this version',
    'Другие версии этих песен не попадают в волну и радар': 'Other versions of these songs stay out of My Wave and the radar',
    'Радар релизов': 'Release Radar',
    'День выпуска': 'Release day',
    'Если клиент был закрыт, выпуск соберётся при следующем запуске': 'If the app was closed, the radar is built on the next launch',
    'Время выпуска': 'Release time',
    'Часовой пояс': 'Time zone',
    'Понедельник': 'Monday',
    'Вторник': 'Tuesday',
    'Среда': 'Wednesday',
    'Четверг': 'Thursday',
    'Пятница': 'Friday',
    'Суббота': 'Saturday',
    'Воскресенье': 'Sunday',
    'Пусто': 'Empty',
    'Трек': 'Track',
    'Артист': 'Artist',
    'Вернуть': 'Restore',
    'Не сейчас': 'Not now',
    'Больше такого': 'More like this',
    'Убрать': 'Remove',
    'до': 'until',

    'Показывать трек в статусе': 'Show track in status',
    'Значок SoundCloud на обложке': 'SoundCloud badge on artwork',
    'Значок GitHub со ссылкой на клиент': 'GitHub badge linking to the client',
    'Кнопка перехода к треку': 'Button to open the track',
    'Вторая строка под ником': 'Second line under your name',
    'Drake вместо SoundCloud': 'Drake instead of SoundCloud',
    'Инкогнито': 'Incognito',
    'Строки карточки': 'Card lines',
    'Первая': 'First',
    'Вторая': 'Second',
    'На обложке': 'On artwork',
    'Подсказка при наведении': 'Tooltip on hover',
    'Название трека': 'Track title',
    'Жанр': 'Genre',
    'Моя волна, если трек из неё': 'My Wave, if the track comes from it',
    'Прослушивания': 'Plays',
    'Как было': 'Reset',
    'Не показывать в Discord': 'Hide from Discord',
    'Артисты через запятую': 'Artists, comma separated',
    'Артисты, которых не видно в Discord': 'Artists hidden from Discord',
    'Жанры через запятую': 'Genres, comma separated',
    'Жанры, которых не видно в Discord': 'Genres hidden from Discord',
    'Инкогнито: Discord не видит, что играет': 'Incognito: Discord doesn’t see what’s playing',
    'Артист в списке скрытых, Discord его не видит': 'This artist is hidden, Discord doesn’t see it',
    'Жанр в списке скрытых, Discord его не видит': 'This genre is hidden, Discord doesn’t see it',
    'Так статус видят в Discord': 'How your status looks in Discord',
    'Сейчас ничего не играет': 'Nothing is playing',
    'Обложка трека': 'Track artwork',
    'Слушать в SoundCloud': 'Listen on SoundCloud',
    'SoundCloud на GitHub': 'SoundCloud on GitHub',
    'Без названия': 'Untitled',
    'Неизвестный артист': 'Unknown artist',
    'Под ником:': 'Under your name:',

    'Текущий аккаунт': 'Current account',
    // Имена аккаунтов по умолчанию, остальные имена это ники с сайта
    'Основной аккаунт': 'Main account',
    'Новый аккаунт': 'New account',
    'Добавить аккаунт': 'Add account',
    'Выйти': 'Log out',
    'Смена аккаунта перезапускает клиент': 'Switching accounts restarts the client',

    'Резервная копия': 'Backup',
    'История прослушиваний, отметки волны, вкус, подборки, архив радара и настройки в одном файле. Лайки, плейлисты и подписки хранит SoundCloud, вход и пароль прокси в копию не входят':
        'Listening history, wave marks, taste, mixes, radar archive and settings in one file. Likes, playlists and follows live on SoundCloud; sign-in and the proxy password are not included',
    'Файл копии': 'Backup file',
    'Лежит только там, куда ты его положишь': 'Stays only where you put it',
    'Сохранить копию…': 'Save backup…',
    'Восстановить…': 'Restore…',
    'Восстановить': 'Restore',
    'Отмена': 'Cancel',
    'Автокопия раз в неделю': 'Weekly auto backup',
    'Сначала выбери папку': 'Choose a folder first',
    'Папка автокопии': 'Auto backup folder',
    'Выбрать…': 'Choose…',
    'Переустановку Windows переживёт папка на другом диске или в облаке. Хранятся пять последних копий':
        'A folder on another drive or in the cloud survives a Windows reinstall. The last five backups are kept',
    'Не выбрана': 'Not chosen',
    'Идёт копирование…': 'Backing up…',
    'Не получилось': 'Failed',
    'Последняя удачная': 'Last successful',
    'Последняя копия': 'Last backup',
    'Копий ещё не было': 'No backups yet',
    'Это не файл резервной копии клиента': 'This is not a client backup file',
    'Копию сделала более новая версия клиента, сначала обнови клиент': 'The backup was made by a newer client version, update the client first',
    'Файл повреждён или обрезан': 'The file is damaged or cut off',
    'Файл слишком большой': 'The file is too large',
    'В файле есть незнакомые части': 'The file has unknown parts',
    'Часть данных в файле испорчена': 'Some data in the file is corrupted',
    'Файл изменился после проверки, выбери его заново': 'The file changed after the check, choose it again',
    'Папка данных клиента не подходит: копия пропадёт вместе с ней': 'The client data folder won’t do: the backup would be lost with it',
    'Папки нет, выбери другую': 'The folder is missing, choose another one',
    'На диске не хватает места': 'Not enough disk space',
    'Нет прав на запись в эту папку': 'No permission to write to this folder',
    'Не получилось прочитать или записать файл': 'Couldn’t read or write the file',
    'Копия уже сохраняется или восстанавливается, подожди': 'A backup is already being saved or restored, please wait',
    'новых': 'new',
    'Копия от': 'Backup from',
    'версия клиента': 'client version',
    'Аккаунт SoundCloud': 'SoundCloud account',
    'открыт сейчас': 'signed in now',
    'Прослушиваний': 'Plays',
    'прослушиваний': 'plays',
    'отметок волны': 'wave marks',
    'убрано из вкуса': 'removed from taste',
    'подборок': 'mixes',
    'выпусков радара': 'radar editions',
    'решений о версиях': 'version decisions',
    'В копии только настройки': 'The backup holds only settings',
    'Настроек в копии': 'Settings in the backup',
    'поменяется': 'will change',
    'В копии другой аккаунт, не тот, что открыт сейчас. Его данные лягут отдельно и появятся, когда войдёшь в него':
        'The backup is from another account, not the one signed in now. Its data is kept separately and shows up when you sign in to it',
    'История, отметки, подборки и радар сливаются с текущими, ничего не удаляется. Настройки берутся из копии':
        'History, marks, mixes and radar are merged with the current ones, nothing is deleted. Settings are taken from the backup',
    'Сохраняю копию…': 'Saving backup…',
    'Копия сохранена': 'Backup saved',
    'Копия не сохранена': 'Backup not saved',
    'Проверяю файл…': 'Checking the file…',
    'Файл не подходит': 'File not accepted',
    'Восстанавливаю…': 'Restoring…',
    'Не восстановлено, данные остались как были': 'Not restored, your data is unchanged',
    'Восстановлено': 'Restored',

    'Разбирать названия треков': 'Parse track titles',
    'Отделяет артиста от названия, когда оба в одной строке': 'Separates the artist from the title when both are in one line',
    'Подключаться через прокси': 'Connect through a proxy',
    'Адрес': 'Host',
    'Адрес прокси': 'Proxy host',
    'Порт': 'Port',
    'Порт прокси': 'Proxy port',
    'Логин': 'Username',
    'Логин прокси': 'Proxy username',
    'Пароль': 'Password',
    'Пароль прокси': 'Proxy password',
    'Отправлять вебхук': 'Send a webhook',
    'https://адрес-вебхука': 'https://webhook-url',
    'Адрес вебхука': 'Webhook URL',
    'Когда трек проигран на': 'When the track has played',
    'Процент проигрывания': 'Played percentage',
    'Пример данных': 'Sample data',
    'Журнал диагностики': 'Diagnostic log',
    'Ошибки и нагрузка, без паролей и названий треков': 'Errors and load, without passwords or track titles',
    'Сохранить': 'Save',
    'Журнал сохранён, его можно отправить для разбора проблемы': 'Log saved, you can send it to have the problem looked into',
    'Не удалось сохранить журнал, попробуй другую папку': 'Couldn’t save the log, try another folder',
    'Папка данных клиента': 'Client data folder',
    'Настройки и история': 'Settings and history',
    'Открыть': 'Open',

    'Проверять обновления': 'Check for updates',
    'Проверить сейчас': 'Check now',
    'Установить и перезапустить': 'Install and restart',
    'Страница релиза': 'Release page',
    'Версия': 'Version',
};
